### PR TITLE
create ros-kinetic-devel branch

### PR DESCRIPTION
**Pull request by benjaminabruzzo**
I see that the changes you made did fix the multiple shooting code.  I forked and branched your original code to make it into a ROS package.  I'm not finished yet, but it does compile and I can run it through the ROS framework.

I still have a significant bit of work to make it more like a ROS package that robots can use.

Also, I had to undo some of the mode advanced c++ code that you generated.  For example, the 'virtual public MatrixFreeGMRES' calls following certain class definitions had to be removed.  

Last, I'm not sure if it is the compilation method that I have set up or the changes to some of the virtual c++ classes, but the CPU time reported by the simulation has been increased approximately tenfold.  If you're familiar with ROS and know how to speed it up again, I would be greatly appreciative of the help.  Otherwise I'll keep working along on my own.

### CODE REVIEW

**Comment by mayataka** [comment]
Thank you for making enable this code running on ROS. 
Sorry for mistaking canceling your pull request. I merge your pull request to master branch by mistake, so can you send pull request again? I'll make a new branch for ROS.

I wonder why you cannot use the 'virtual public MatrixFreeGMRES'. The class 'InitCGMRES' remains inherited from the 'MatrixFreeGMRES', which means you can use inheritance in some case.  Which class you cannot inherit from the 'MatrixFreeGMRES'?

About the CPU time to be run on ROS, I have no idea because I have never use ROS.

**Comment by benjaminabruzzo** [comment]
I made the pull request again, it seems like github is trying to merge my
fork with your master branch.  I'm not very experienced with github either,
so maybe I'm creating the pull request incorrectly.

I do not think ROS is the cause of the compilation errors, I think it is
how I set up the main function.  The main function in my ros-compilable
code is in mayataka_nmpc.cpp.   Most of the code is a class definition
using the Simulator, MultipleShootingCGMRES, and ContinuationGMRES classes
as objects to the class.  Because of the way they are created and
initialized, the virtual and inherited functions were causing compile
errors.

Maybe there is a better way to set up the mayataka_nmpc class.  A different
project in which I use the same code structure is here:
https://github.com/westpoint-robotics/usma_ardrone/blob/master/optitrack_controller/src/optitrackAutopilot.cpp

The reason I set it up this way is for the ROS communication system.  For
example, on line 131 the updateFacePose function is waiting for a Twist
message from the ROS network, and when that message is received, the
function is triggered (this is linked to the constructor command on line
96).  I'm not very good at c++, so there might be a way to improve the code
to run more quickly.

My plan is to remove the simulation from this code and have the nmpc
triggered by new estimates of the controlled system to then determine the
optimal control signal for the robot.

-.- -.. ..--- . -.- -
Benjamin

**Comment by benjaminabruzzo** [comment]
You could try making your own branch and call it something else.  I can
send a pull request against that branch instead of the master.  That might
fix things.
-.- -.. ..--- . -.- -
Benjamin

**Comment by mayataka** [comment]
I made a new branch named ros-kinetic-devel.

**Pull request merged**
